# Generated by Django 5.2.12 on 2026-06-05 05:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_initial'),
        ('catalog', '0002_initial'),
        ('tenancy', '0004_tenantbrandingmodel_facebook_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_status', models.CharField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', help_text='Current internal workflow stage of this quote.', max_length=16, verbose_name='Workflow status')),
                ('customer_name', models.CharField(blank=True, default='', help_text='Name of the person requesting the quote.', max_length=255, verbose_name='Customer name')),
                ('customer_email', models.EmailField(blank=True, default='', help_text='Email address used to follow up on this quote.', max_length=254, verbose_name='Customer email')),
                ('customer_phone', models.CharField(blank=True, default='', help_text='Phone number used to follow up on this quote.', max_length=64, verbose_name='Customer phone')),
                ('company_name', models.CharField(blank=True, default='', help_text='Optional company name when the quote belongs to a business customer.', max_length=255, verbose_name='Company')),
                ('tax_id', models.CharField(blank=True, default='', help_text='Optional tax or company identification reference.', max_length=64, verbose_name='Tax ID')),
                ('notes', models.TextField(blank=True, default='', help_text='Private notes not intended for customers.', verbose_name='Internal notes')),
                ('requested_at', models.DateTimeField(blank=True, help_text='When the quote was formally requested.', null=True, verbose_name='Requested at')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the internal workflow for this quote reached a terminal resolution.', null=True, verbose_name='Resolved at')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this quote was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this quote was last updated.', verbose_name='Updated at')),
                ('cart', models.ForeignKey(blank=True, help_text='Optional cart that originated this quote.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='cart.cartmodel', verbose_name='Source cart')),
                ('tenant', models.ForeignKey(help_text='Business that owns this quote and the follow-up around it.', on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='tenancy.tenantmodel', verbose_name='Business')),
                ('user', models.ForeignKey(blank=True, help_text='Optional customer account related to this quote.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to=settings.AUTH_USER_MODEL, verbose_name='Customer account')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='QuoteItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(help_text='Product name captured when this quote item was created.', max_length=255, verbose_name='Product name snapshot')),
                ('sku_snapshot', models.CharField(blank=True, default='', help_text='SKU captured when this quote item was created.', max_length=64, verbose_name='SKU snapshot')),
                ('attributes_snapshot', models.JSONField(blank=True, default=dict, help_text='Variant attributes captured when this quote item was created.', verbose_name='Attribute snapshot')),
                ('unit_price_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text='Unit price captured when this quote item was created.', max_digits=12, null=True, verbose_name='Unit price snapshot')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units requested for this quote item.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional internal note for this specific quote item.', verbose_name='Item notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this quote item was created.', verbose_name='Created at')),
                ('product', models.ForeignKey(blank=True, help_text='Optional product reference kept while the catalog product still exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='catalog.productmodel', verbose_name='Product')),
                ('variant', models.ForeignKey(blank=True, help_text='Optional variant reference kept while the catalog variant still exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='catalog.productvariantmodel', verbose_name='Variant')),
                ('quote', models.ForeignKey(help_text='Quote this line item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotation.quotemodel', verbose_name='Quote')),
            ],
            options={
                'verbose_name': 'Quote item',
                'verbose_name_plural': 'Quote items',
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
