# Generated by Django 5.2.12 on 2026-04-14 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
        ('tenancy', '0003_alter_tenantmodel_business_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotemodel',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='tenancy.tenantmodel'),
            preserve_default=False,
        ),
    ]
