# Generated by Django 5.2.12 on 2026-04-15 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('catalog', '0004_alter_productimagemodel_alt_text_and_more'),
        ('quotation', '0002_quotemodel_tenant'),
        ('tenancy', '0003_alter_tenantmodel_business_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitemmodel',
            name='attributes_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Variant attributes captured when this quote item was created.', verbose_name='Attribute snapshot'),
        ),
        migrations.AlterField(
            model_name='quoteitemmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this quote item was created.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='quoteitemmodel',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Optional internal note for this specific quote item.', verbose_name='Item notes'),
        ),
        migrations.AlterField(
            model_name='quoteitemmodel',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Optional product reference kept while the catalog product still exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='catalog.productmodel', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='quoteitemmodel',
            name='product_name_snapshot',
            field=models.CharField(help_text='Product name captured when this quote item was created.', max_length=255, verbose_name='Product name snapshot'),
        ),
        migrations.AlterField(
            model_name='quoteitemmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of units requested for this quote item.', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='quoteitemmodel',
            name='quote',
            field=models.ForeignKey(help_text='Quote this line item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotation.quotemodel', verbose_name='Quote'),
        ),
        migrations.AlterField(
            model_name='quoteitemmodel',
            name='sku_snapshot',
            field=models.CharField(blank=True, default='', help_text='SKU captured when this quote item was created.', max_length=64, verbose_name='SKU snapshot'),
        ),
        migrations.AlterField(
            model_name='quoteitemmodel',
            name='unit_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Unit price captured when this quote item was created.', max_digits=12, null=True, verbose_name='Unit price snapshot'),
        ),
        migrations.AlterField(
            model_name='quoteitemmodel',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Optional variant reference kept while the catalog variant still exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='catalog.productvariantmodel', verbose_name='Variant'),
        ),
        migrations.AlterField(
            model_name='quotemodel',
            name='answered_at',
            field=models.DateTimeField(blank=True, help_text='When the customer answered this quote.', null=True, verbose_name='Answered at'),
        ),
        migrations.AlterField(
            model_name='quotemodel',
            name='cart',
            field=models.ForeignKey(blank=True, help_text='Optional cart that originated this quote.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='cart.cartmodel', verbose_name='Source cart'),
        ),
        migrations.AlterField(
            model_name='quotemodel',
            name='company_name',
            field=models.CharField(blank=True, default='', help_text='Optional company name when the quote belongs to a business customer.', max_length=255, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='quotemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this quote was created.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='quotemodel',
            name='customer_email',
            field=models.EmailField(blank=True, default='', help_text='Email address your team can use to follow up on this quote.', max_length=254, verbose_name='Customer email'),
        ),
        migrations.AlterField(
            model_name='quotemodel',
            name='customer_name',
            field=models.CharField(blank=True, default='', help_text='Name of the person requesting the quote.', max_length=255, verbose_name='Customer name'),
        ),
        migrations.AlterField(
            model_name='quotemodel',
            name='customer_phone',
            field=models.CharField(blank=True, default='', help_text='Phone number your team can use to follow up on this quote.', max_length=64, verbose_name='Customer phone'),
        ),
        migrations.AlterField(
            model_name='quotemodel',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Private context for your team. Customers do not need to see this text.', verbose_name='Internal notes'),
        ),
        migrations.AlterField(
            model_name='quotemodel',
            name='requested_at',
            field=models.DateTimeField(blank=True, help_text='When the quote was formally requested.', null=True, verbose_name='Requested at'),
        ),
        migrations.AlterField(
            model_name='quotemodel',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='When the quote was sent back to the customer.', null=True, verbose_name='Sent at'),
        ),
        migrations.AlterField(
            model_name='quotemodel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('sent', 'Sent'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', help_text='Current stage of this quote in your sales follow-up.', max_length=16, verbose_name='Quote status'),
        ),
        migrations.AlterField(
            model_name='quotemodel',
            name='tax_id',
            field=models.CharField(blank=True, default='', help_text='Optional tax or company identification reference.', max_length=64, verbose_name='Tax ID'),
        ),
        migrations.AlterField(
            model_name='quotemodel',
            name='tenant',
            field=models.ForeignKey(help_text='Business that owns this quote and the follow-up around it.', on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='tenancy.tenantmodel', verbose_name='Business'),
        ),
        migrations.AlterField(
            model_name='quotemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this quote was last updated.', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='quotemodel',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Optional customer account related to this quote.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to=settings.AUTH_USER_MODEL, verbose_name='Customer account'),
        ),
    ]
