# Generated by Django 5.2.12 on 2026-04-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_alter_quoteitemmodel_attributes_snapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotemodel',
            name='answered_at',
        ),
        migrations.RemoveField(
            model_name='quotemodel',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='quotemodel',
            name='status',
        ),
        migrations.AddField(
            model_name='quotemodel',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='When the internal workflow for this quote reached a terminal resolution.', null=True, verbose_name='Resolved at'),
        ),
        migrations.AddField(
            model_name='quotemodel',
            name='workflow_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', help_text='Current internal workflow stage of this quote for your team.', max_length=16, verbose_name='Workflow status'),
        ),
    ]
