# Generated by Django 5.2.12 on 2026-04-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_remove_quotemodel_answered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotemodel',
            name='customer_email',
            field=models.EmailField(blank=True, default='', help_text='Email address used to follow up on this quote.', max_length=254, verbose_name='Customer email'),
        ),
        migrations.AlterField(
            model_name='quotemodel',
            name='customer_phone',
            field=models.CharField(blank=True, default='', help_text='Phone number used to follow up on this quote.', max_length=64, verbose_name='Customer phone'),
        ),
        migrations.AlterField(
            model_name='quotemodel',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Private notes not intended for customers.', verbose_name='Internal notes'),
        ),
        migrations.AlterField(
            model_name='quotemodel',
            name='workflow_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', help_text='Current internal workflow stage of this quote.', max_length=16, verbose_name='Workflow status'),
        ),
    ]
