# Generated by Django 5.2.12 on 2026-04-17 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_alter_quotemodel_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitemmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of units requested for this quote item.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity'),
        ),
    ]
