""" Shared base widget behavior for JSON key-value editors. """

from typing import Any
from django import forms
from django.utils.translation import gettext_lazy as _
from unfold.widgets import INPUT_CLASSES
from core.forms.widgets.common_classes import UNFOLD_READONLY_VALUE_CLASSES


class BaseJsonKeyValueWidget(forms.Widget):
    """ Share labels, styling, and submitted-data helpers for key-value widgets. """

    class Media:
        """ Load shared styles for JSON key-value widgets. """

        css = {
            "all": ("core/forms/widgets/json_key_value_base.css",),
        }

    def __init__(
        self,
        attrs: dict[str, Any] | None = None,
        *,
        key_label: str | None = None,
        value_label: str | None = None,
        add_label: str | None = None,
        remove_label: str | None = None,
    ) -> None:
        """ Initialize shared key-value widget configuration.

        Args:
            attrs: Optional widget HTML attributes.
            key_label: Optional label for the key column.
            value_label: Optional label for the value column.
            add_label: Optional label for the add-row action.
            remove_label: Optional label for the remove-row action.
        """
        super().__init__(attrs)
        self.key_label = key_label or _("Key")
        self.value_label = value_label or _("Value")
        self.add_label = add_label or _("Add row")
        self.remove_label = remove_label or _("Remove row")

    def get_input_classes(self) -> str:
        """ Return Unfold-compatible text input classes for widget rows.

        Returns:
            str: CSS classes aligned with Unfold text inputs.
        """
        return " ".join(INPUT_CLASSES)

    def get_add_button_classes(self) -> str:
        """ Return Unfold-compatible classes for the add-row action.

        Returns:
            str: CSS classes aligned with a secondary admin action.
        """
        classes = [
            "border",
            "border-base-200",
            "cursor-pointer",
            "font-medium",
            "px-3",
            "py-2",
            "rounded-default",
            "shadow-xs",
            "text-font-important-light",
            "text-sm",
            "transition-all",
            "whitespace-nowrap",
            "hover:bg-base-50",
            "dark:border-base-700",
            "dark:text-font-important-dark",
            "dark:hover:bg-base-900",
        ]
        return " ".join(classes)

    def get_remove_button_classes(self) -> str:
        """ Return Unfold-compatible classes for the remove-row action.

        Returns:
            str: CSS classes aligned with a compact destructive admin action.
        """
        classes = [
            "border",
            "border-base-200",
            "cursor-pointer",
            "flex",
            "font-medium",
            "h-[38px]",
            "items-center",
            "justify-center",
            "px-0",
            "py-0",
            "rounded-default",
            "shadow-xs",
            "text-center",
            "text-red-600",
            "text-sm",
            "transition-all",
            "w-[38px]",
            "hover:bg-red-50",
            "dark:border-base-700",
            "dark:text-red-500",
            "dark:hover:bg-red-500/20",
        ]
        return " ".join(classes)

    def get_display_classes(self, *, extra_classes: tuple[str, ...] = ()) -> str:
        """ Return Unfold-compatible classes for readonly row values.

        Args:
            extra_classes: Optional local classes appended to the native Unfold classes.

        Returns:
            str: CSS classes aligned with Unfold readonly fields.
        """
        return " ".join([*UNFOLD_READONLY_VALUE_CLASSES, *extra_classes])

    def is_readonly_attrs(self, attrs: dict[str, Any]) -> bool:
        """ Return whether widget attrs represent a locked display state.

        Args:
            attrs: Widget attributes generated by Django.

        Returns:
            bool: True when readonly or disabled attrs are present.
        """
        return bool(getattr(self, "read_only", False) or attrs.get("readonly") or attrs.get("disabled"))

    def has_submitted_widget(self, data: Any, name: str) -> bool:
        """ Return whether the widget was present in submitted form data.

        Args:
            data: Submitted form data.
            name: Bound field name, including form prefixes.

        Returns:
            bool: ``True`` when the widget's presence marker was submitted.
        """
        present_key = f"{name}__present"
        if hasattr(data, "getlist"):
            return bool(data.getlist(present_key))

        return present_key in data

    def value_omitted_from_owned_data(self, data: Any, name: str, *, suffixes: tuple[str, ...]) -> bool:
        """ Return whether a widget was absent based on its owned input suffixes.

        Args:
            data: Submitted form data.
            name: Bound field name, including form prefixes.
            suffixes: Input suffixes owned by the concrete widget.

        Returns:
            bool: ``True`` only when none of the widget-owned inputs were submitted.
        """
        if self.has_submitted_widget(data, name):
            return False

        return not any(
            self.get_repeated_values(data, f"{name}__{suffix}")
            for suffix in suffixes
        )

    def get_repeated_values(self, data: Any, key: str) -> list[Any]:
        """ Return submitted values from QueryDict-like or plain dictionary data.

        Args:
            data: Submitted form data.
            key: Submitted input name.

        Returns:
            list[Any]: Values submitted for the provided key.
        """
        if hasattr(data, "getlist"):
            return list(data.getlist(key))

        value = data.get(key, "")
        if isinstance(value, list | tuple):
            return list(value)

        return [value] if value != "" else []
