# Generated by Django 5.2.12 on 2026-04-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='tenants',
            field=models.ManyToManyField(blank=True, help_text='Businesses this account can access through business access records.', related_name='users', through='tenancy.TenantMembershipModel', to='tenancy.tenantmodel', verbose_name='Businesses'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
