# Generated by Django 5.2.12 on 2026-04-10 02:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Public name used to identify this business across the admin.', max_length=255, verbose_name='Business name')),
                ('slug', models.SlugField(help_text='Stable URL-friendly identifier for this business.', max_length=255, unique=True, verbose_name='Business slug')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to hide the business from active business selection and day-to-day use.', verbose_name='Business active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TenantGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(help_text='Django auth group scoped to the selected business.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_binding', to='auth.group', verbose_name='Permission group')),
                ('tenant', models.ForeignKey(help_text='Business that owns this permission group.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_groups', to='tenancy.tenantmodel', verbose_name='Business')),
            ],
            options={
                'verbose_name': 'Business group',
                'verbose_name_plural': 'Business groups',
                'ordering': ('tenant__name', 'group__name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TenantBrandingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='Optional public name used instead of the business name when branding is shown.', max_length=255, verbose_name='Display name')),
                ('logo_light', models.ImageField(blank=True, help_text='Logo variant intended for light backgrounds.', upload_to='branding/logos/', verbose_name='Light logo')),
                ('logo_dark', models.ImageField(blank=True, help_text='Logo variant intended for dark backgrounds.', upload_to='branding/logos/', verbose_name='Dark logo')),
                ('icon_light', models.ImageField(blank=True, help_text='Compact icon variant intended for light backgrounds.', upload_to='branding/icons/', verbose_name='Light icon')),
                ('icon_dark', models.ImageField(blank=True, help_text='Compact icon variant intended for dark backgrounds.', upload_to='branding/icons/', verbose_name='Dark icon')),
                ('favicon_light', models.ImageField(blank=True, help_text='Favicon variant intended for light browser themes or light backgrounds.', upload_to='branding/favicons/', verbose_name='Light favicon')),
                ('favicon_dark', models.ImageField(blank=True, help_text='Favicon variant intended for dark browser themes or dark backgrounds.', upload_to='branding/favicons/', verbose_name='Dark favicon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(help_text='Business that owns this branding configuration.', on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='tenancy.tenantmodel', verbose_name='Business')),
            ],
            options={
                'verbose_name': 'Business branding',
                'verbose_name_plural': 'Business branding',
                'ordering': ('tenant__name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TenantMembershipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('master', 'Master'), ('owner', 'Owner'), ('operator', 'Operator')], default='owner', help_text='Role this account will have inside the selected business.', max_length=16, verbose_name='Business role')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to keep the access record without allowing day-to-day access.', verbose_name='Access active')),
                ('is_primary', models.BooleanField(default=False, help_text='Marks this as the default business access used as a fallback context for the account.', verbose_name='Primary access')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Account that receives this business access.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('tenant', models.ForeignKey(help_text='Business where this account receives access.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.tenantmodel', verbose_name='Business')),
            ],
            options={
                'verbose_name': 'Business access',
                'verbose_name_plural': 'Business access',
                'ordering': ('tenant__name', 'user__username', 'id'),
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user'), name='tenant_membership_unique_tenant_user'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='tenant_membership_unique_primary_per_user')],
            },
        ),
    ]
