# Generated by Django 5.2.12 on 2026-04-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmodel',
            name='business_email',
            field=models.EmailField(blank=True, help_text='General contact email for this business.', max_length=254, verbose_name='Business email'),
        ),
        migrations.AddField(
            model_name='tenantmodel',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional public phone number for this business.', max_length=50, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='tenantmodel',
            name='support_email',
            field=models.EmailField(blank=True, help_text='Optional support contact email shown in tenant-aware surfaces such as email footers.', max_length=254, verbose_name='Support email'),
        ),
        migrations.AddField(
            model_name='tenantmodel',
            name='website_url',
            field=models.URLField(blank=True, help_text='Optional public website URL for this business.', verbose_name='Website URL'),
        ),
    ]
