# Generated by Django 5.2.12 on 2026-04-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_tenantmodel_business_email_tenantmodel_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantmodel',
            name='business_email',
            field=models.EmailField(blank=True, help_text='Main contact email for this business.', max_length=254, verbose_name='Business email'),
        ),
        migrations.AlterField(
            model_name='tenantmodel',
            name='support_email',
            field=models.EmailField(blank=True, help_text='Optional support email shown in emails and messages sent for this business.', max_length=254, verbose_name='Support email'),
        ),
        migrations.AlterField(
            model_name='tenantmodel',
            name='website_url',
            field=models.URLField(blank=True, help_text='Optional public website URL for this business.', verbose_name='Website'),
        ),
    ]
