# Generated by Django 5.2.12 on 2026-04-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_alter_tenantmodel_business_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantbrandingmodel',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Public Facebook page used in the storefront footer and contact surfaces.', verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='tenantbrandingmodel',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Public Instagram profile used in the storefront footer and contact surfaces.', verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='tenantbrandingmodel',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Public LinkedIn profile or company page used in the storefront footer and contact surfaces.', verbose_name='LinkedIn URL'),
        ),
    ]
