# Generated by Django 5.2.12 on 2026-06-05 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0004_tenantbrandingmodel_facebook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Use the brand name your team and customers already recognize.', max_length=255, verbose_name='Brand name')),
                ('slug', models.SlugField(help_text='Usually created from the brand name. Adjust it only when you need a custom URL.', max_length=255, verbose_name='URL slug')),
                ('description', models.TextField(blank=True, default='', help_text='Optional. Add short internal guidance about when this brand should be used.', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Disable this brand when you want to stop using it without deleting its history.', verbose_name='Available for products')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='tenancy.tenantmodel', verbose_name='Business')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('tenant', 'slug'), name='masterdata_brand_slug_unique_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Use the category name your team will recognize while organizing the business catalog.', max_length=255, verbose_name='Category name')),
                ('slug', models.SlugField(help_text='Usually created from the category name. Adjust it only when you need a custom URL.', max_length=255, verbose_name='URL slug')),
                ('description', models.TextField(blank=True, default='', help_text='Optional. Add short guidance so your team understands when to use this category.', verbose_name='Description')),
                ('banner', models.ImageField(blank=True, help_text='Optional public banner image for category pages and featured category cards.', upload_to='masterdata/categories/banners/', verbose_name='Banner')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower values appear first when categories are listed.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Disable this category when you want to stop offering it without deleting its history.', verbose_name='Available for products')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this root category when building curated public storefront sections.', verbose_name='Featured on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('parent', models.ForeignKey(blank=True, help_text='Optional. Leave empty to keep this category at the root level of the business catalog.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='masterdata.categorymodel', verbose_name='Parent category')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tenancy.tenantmodel', verbose_name='Business')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('sort_order', 'name'),
                'constraints': [models.UniqueConstraint(fields=('tenant', 'slug'), name='masterdata_category_slug_unique_per_tenant')],
            },
        ),
    ]
