# Generated by Django 5.2.12 on 2026-04-15 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
        ('tenancy', '0003_alter_tenantmodel_business_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='tenancy.tenantmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tenancy.tenantmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='brandmodel',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='masterdata_brand_slug_unique_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='categorymodel',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='masterdata_category_slug_unique_per_tenant'),
        ),
    ]
