# Generated by Django 5.2.12 on 2026-04-16 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_brandmodel_tenant_categorymodel_tenant_and_more'),
        ('tenancy', '0003_alter_tenantmodel_business_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional. Add short internal guidance about when this brand should be used.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Disable this brand when you want to stop using it without deleting its history.', verbose_name='Available for products'),
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='name',
            field=models.CharField(help_text='Use the brand name your team and customers already recognize.', max_length=255, verbose_name='Brand name'),
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='slug',
            field=models.SlugField(help_text='Usually created from the brand name. Adjust it only when you need a custom URL.', max_length=255, verbose_name='URL slug'),
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='tenancy.tenantmodel', verbose_name='Business'),
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional. Add short guidance so your team understands when to use this category.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Disable this category when you want to stop offering it without deleting its history.', verbose_name='Available for products'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(help_text='Use the category name your team will recognize while organizing the business catalog.', max_length=255, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Optional. Leave empty to keep this category at the root level of the business catalog.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='masterdata.categorymodel', verbose_name='Parent category'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='slug',
            field=models.SlugField(help_text='Usually created from the category name. Adjust it only when you need a custom URL.', max_length=255, verbose_name='URL slug'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower values appear first when categories are listed.', verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tenancy.tenantmodel', verbose_name='Business'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
