# Generated by Django 5.2.12 on 2026-04-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_alter_brandmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='banner',
            field=models.ImageField(blank=True, help_text='Optional public banner image for category pages and featured category cards.', upload_to='masterdata/categories/banners/', verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Highlight this root category when building curated public storefront sections.', verbose_name='Featured on the site'),
        ),
    ]
