# Generated by Django 5.2.12 on 2026-06-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload the product image shown in the catalog and admin.', upload_to='catalog/products/images/', verbose_name='Image file')),
                ('alt_text', models.CharField(blank=True, default='', help_text='Short accessibility description of what appears in the image.', max_length=255, verbose_name='Alt text')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower values appear first in product galleries.', verbose_name='Display order')),
                ('is_primary', models.BooleanField(default=False, help_text='Use this image as the main visual for the product or variant.', verbose_name='Primary image')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this image was created.', verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Product image',
                'verbose_name_plural': 'Product images',
                'ordering': ('product_id', 'sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer-facing name shown across the catalog.', max_length=255, verbose_name='Product name')),
                ('slug', models.SlugField(help_text='Short URL-friendly identifier used in product links.', max_length=255, verbose_name='URL slug')),
                ('short_description', models.CharField(blank=True, default='', help_text='Short summary for compact cards and product lists.', max_length=255, verbose_name='Short description')),
                ('description', models.TextField(blank=True, default='', help_text='Full product description with the details customers should read.', verbose_name='Full description')),
                ('sku_base', models.CharField(help_text='Required product-family reference used when variants do not define their own SKU.', max_length=64, verbose_name='Base SKU')),
                ('is_active', models.BooleanField(default=True, help_text='Turn this off to hide the product without deleting it.', verbose_name='Visible to customers')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this product in featured catalog sections.', verbose_name='Featured product')),
                ('requires_quote', models.BooleanField(default=True, help_text='Enable this when customers should request a quote instead of buying directly.', verbose_name='Request through quote')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this product was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this product was last updated.', verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductVariantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Optional customer-facing name for this specific variant.', max_length=255, verbose_name='Variant name')),
                ('sku', models.CharField(blank=True, default='', help_text='Optional unique internal reference. Leave it empty to use the parent product base SKU.', max_length=64, verbose_name='Variant SKU')),
                ('attributes_json', models.JSONField(blank=True, default=dict, help_text='Structured attributes such as size, color, or packaging.', verbose_name='Variant attributes')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional direct price for this variant when it does not rely only on quotes.', max_digits=12, null=True, verbose_name='Price')),
                ('is_default', models.BooleanField(default=False, help_text='Use this as the preselected variant for the product.', verbose_name='Default variant')),
                ('is_active', models.BooleanField(default=True, help_text='Turn this off to keep the variant without offering it.', verbose_name='Available for selection')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower values appear first in admin and customer-facing variant lists.', verbose_name='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this variant was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this variant was last updated.', verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Product variant',
                'verbose_name_plural': 'Product variants',
                'ordering': ('product_id', 'sort_order', 'name', 'id'),
            },
        ),
    ]
