# Generated by Django 5.2.12 on 2026-06-05 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('masterdata', '0001_initial'),
        ('tenancy', '0004_tenantbrandingmodel_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Optional brand shown with this product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='masterdata.brandmodel', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Optional category used to organize this product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='masterdata.categorymodel', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this product and its related catalog data.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenancy.tenantmodel', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='productimagemodel',
            name='product',
            field=models.ForeignKey(help_text='Product this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.productmodel', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='productvariantmodel',
            name='product',
            field=models.ForeignKey(help_text='Product this variant belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.productmodel', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='productimagemodel',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Optional variant shown by this image when it is not shared across the whole product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='catalog.productvariantmodel', verbose_name='Variant'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['tenant', 'is_active', 'is_featured'], name='catalog_pro_tenant__f62023_idx'),
        ),
        migrations.AddConstraint(
            model_name='productmodel',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='catalog_product_slug_unique_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='productvariantmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('product',), name='catalog_variant_one_default_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productvariantmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('sku',), name='catalog_variant_sku_unique_when_present'),
        ),
        migrations.AddConstraint(
            model_name='productimagemodel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('variant__isnull', True)), fields=('product',), name='catalog_image_one_primary_root_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productimagemodel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('variant__isnull', False)), fields=('variant',), name='catalog_image_one_primary_per_variant'),
        ),
    ]
