# Generated by Django 5.2.12 on 2026-04-14 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_productmodel_short_description'),
        ('masterdata', '0001_initial'),
        ('tenancy', '0003_alter_tenantmodel_business_email_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productmodel',
            name='catalog_pro_is_acti_2de5a8_idx',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenancy.tenantmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['tenant', 'is_active', 'is_featured'], name='catalog_pro_tenant__f62023_idx'),
        ),
        migrations.AddConstraint(
            model_name='productmodel',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='catalog_product_slug_unique_per_tenant'),
        ),
    ]
