# Generated by Django 5.2.12 on 2026-04-14 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_productmodel_catalog_pro_is_acti_2de5a8_idx_and_more'),
        ('masterdata', '0001_initial'),
        ('tenancy', '0003_alter_tenantmodel_business_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagemodel',
            name='alt_text',
            field=models.CharField(blank=True, default='', help_text='Short accessibility description of what appears in the image.', max_length=255, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this image was created.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='image',
            field=models.ImageField(help_text='Upload the product image shown in the catalog and admin.', upload_to='catalog/products/images/', verbose_name='Image file'),
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Use this image as the main visual for the product or variant.', verbose_name='Primary image'),
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='product',
            field=models.ForeignKey(help_text='Product this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.productmodel', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower values appear first in product galleries.', verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Optional variant shown by this image when it is not shared across the whole product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='catalog.productvariantmodel', verbose_name='Variant'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Optional brand shown with this product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='masterdata.brandmodel', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Optional category used to organize this product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='masterdata.categorymodel', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this product was created.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Full product description with the details customers should read.', verbose_name='Full description'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Turn this off to hide the product without deleting it.', verbose_name='Visible to customers'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Highlight this product in featured catalog sections.', verbose_name='Featured product'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(help_text='Customer-facing name shown across the catalog.', max_length=255, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='requires_quote',
            field=models.BooleanField(default=True, help_text='Enable this when customers should request a quote instead of buying directly.', verbose_name='Request through quote'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='short_description',
            field=models.CharField(blank=True, default='', help_text='Short summary for compact cards and product lists.', max_length=255, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='sku_base',
            field=models.CharField(blank=True, default='', help_text='Internal base reference used to identify this product family and its variants.', max_length=64, verbose_name='Base SKU'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(help_text='Short URL-friendly identifier used in product links.', max_length=255, verbose_name='URL slug'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this product and its related catalog data.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenancy.tenantmodel', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this product was last updated.', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='attributes_json',
            field=models.JSONField(blank=True, default=dict, help_text='Structured attributes such as size, color, or packaging.', verbose_name='Variant attributes'),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this variant was created.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Turn this off to keep the variant without offering it.', verbose_name='Available for selection'),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Use this as the preselected variant for the product.', verbose_name='Default variant'),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Optional customer-facing name for this specific variant.', max_length=255, verbose_name='Variant name'),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional direct price for this variant when it does not rely only on quotes.', max_digits=12, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='product',
            field=models.ForeignKey(help_text='Product this variant belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.productmodel', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='sku',
            field=models.CharField(help_text='Unique internal reference for this variant.', max_length=64, unique=True, verbose_name='Variant SKU'),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower values appear first in admin and customer-facing variant lists.', verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this variant was last updated.', verbose_name='Updated at'),
        ),
    ]
