# Generated by Django 5.2.12 on 2026-04-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_productimagemodel_alt_text_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productimagemodel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('variant__isnull', True)), fields=('product',), name='catalog_image_one_primary_root_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productimagemodel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('variant__isnull', False)), fields=('variant',), name='catalog_image_one_primary_per_variant'),
        ),
    ]
