# Generated by Django 5.2.12 on 2026-06-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productimagemodel_catalog_image_one_primary_root_per_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantmodel',
            name='sku',
            field=models.CharField(blank=True, default='', help_text='Optional unique internal reference. Leave it empty to use the parent product base SKU.', max_length=64, verbose_name='Variant SKU'),
        ),
        migrations.AddConstraint(
            model_name='productvariantmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('sku',), name='catalog_variant_sku_unique_when_present'),
        ),
    ]
