# Generated by Django 5.2.12 on 2026-06-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_productvariantmodel_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='sku_base',
            field=models.CharField(help_text='Required product-family reference used when variants do not define their own SKU.', max_length=64, verbose_name='Base SKU'),
        ),
    ]
