# Generated by Django 5.2.12 on 2026-06-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='How many units of the selected product the cart currently holds.', verbose_name='Quantity')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional runtime notes captured for this cart line.', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this cart item was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this cart item was last updated.', verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Cart item',
                'verbose_name_plural': 'Cart items',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', help_text='Session identifier used when the cart is not tied to a signed-in customer account.', max_length=64, verbose_name='Session key')),
                ('status', models.CharField(choices=[('active', 'Active'), ('converted', 'Converted'), ('abandoned', 'Abandoned')], default='active', help_text='Current lifecycle stage of this cart in the runtime flow.', max_length=16, verbose_name='Cart status')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration timestamp used by runtime cleanup or follow-up rules.', null=True, verbose_name='Expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this cart was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this cart was last updated.', verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
    ]
