# Generated by Django 5.2.12 on 2026-06-05 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('catalog', '0001_initial'),
        ('tenancy', '0004_tenantbrandingmodel_facebook_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemmodel',
            name='product',
            field=models.ForeignKey(help_text='Product currently selected in this cart line.', on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='catalog.productmodel', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='cartitemmodel',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Optional variant currently selected for this cart line.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='catalog.productvariantmodel', verbose_name='Variant'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='tenant',
            field=models.ForeignKey(help_text='Business that owns this cart and the runtime activity around it.', on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='tenancy.tenantmodel', verbose_name='Business'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Optional customer account currently associated with this cart.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Customer account'),
        ),
        migrations.AddField(
            model_name='cartitemmodel',
            name='cart',
            field=models.ForeignKey(help_text='Cart this line belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cartmodel', verbose_name='Cart'),
        ),
        migrations.AddConstraint(
            model_name='cartmodel',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), models.Q(('session_key', ''), _negated=True), _connector='OR'), name='cart_requires_user_or_session_key'),
        ),
        migrations.AddConstraint(
            model_name='cartitemmodel',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'variant'), name='cart_item_unique_cart_product_variant'),
        ),
        migrations.AddConstraint(
            model_name='cartitemmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('cart', 'product'), name='cart_item_unique_cart_product_without_variant'),
        ),
    ]
