# Generated by Django 5.2.12 on 2026-04-16 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartmodel_tenant'),
        ('catalog', '0004_alter_productimagemodel_alt_text_and_more'),
        ('tenancy', '0003_alter_tenantmodel_business_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='cart',
            field=models.ForeignKey(help_text='Cart this line belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cartmodel', verbose_name='Cart'),
        ),
        migrations.AlterField(
            model_name='cartitemmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this cart item was created.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='cartitemmodel',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Optional runtime notes captured for this cart line.', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='cartitemmodel',
            name='product',
            field=models.ForeignKey(help_text='Product currently selected in this cart line.', on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='catalog.productmodel', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='cartitemmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='How many units of the selected product the cart currently holds.', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='cartitemmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this cart item was last updated.', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='cartitemmodel',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Optional variant currently selected for this cart line.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='catalog.productvariantmodel', verbose_name='Variant'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this cart was created.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional expiration timestamp used by runtime cleanup or follow-up rules.', null=True, verbose_name='Expires at'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='session_key',
            field=models.CharField(blank=True, default='', help_text='Session identifier used when the cart is not tied to a signed-in customer account.', max_length=64, verbose_name='Session key'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('converted', 'Converted'), ('abandoned', 'Abandoned')], default='active', help_text='Current lifecycle stage of this cart in the runtime flow.', max_length=16, verbose_name='Cart status'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='tenant',
            field=models.ForeignKey(help_text='Business that owns this cart and the runtime activity around it.', on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='tenancy.tenantmodel', verbose_name='Business'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this cart was last updated.', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Optional customer account currently associated with this cart.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Customer account'),
        ),
    ]
