""" Shared tenant-aware behavior for media storage backends. """

from core.config.storage.media_storage.paths.tenant_media_path_builder import TenantMediaPathBuilder


class TenantAwareMediaStorageMixin:
    """ Prefix generated media object names with the active tenant folder. """

    path_builder_class = TenantMediaPathBuilder

    def generate_filename(self, filename: str) -> str:
        """ Normalize one generated media path with the active tenant folder.

        Args:
            filename: Relative media path generated by the field or caller.

        Returns:
            str: Tenant-aware generated media path.
        """
        normalized_filename = self.path_builder_class.build_tenant_media_name(filename)
        return super().generate_filename(normalized_filename)
